version: '3'
services:
  calculation-service:
    build:
      context: ./calculation-service
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    env_file:
      - .env
    depends_on:
      - quadratic-equation-solver
  quadratic-equation-solver:
    build:
      context: ./quadratic-equation-solver
      dockerfile: Dockerfile
    ports:
      - 8082:8080
